### PR TITLE
Add a circular frequency visualizer

### PR DESCRIPTION
**Pull request by jacobpgallagher**
In case you want another visualizer in the repo.

### CODE REVIEW

**Comment by hackingbeauty** [comment]
Hi Jacob, thank you for contributing.

I pulled down your PR and changed the visual settings to "frequencyCircles" but nothing happens.  Did you visually test this on your end?  What am I supposed to see?

Thanks!

**Comment by jacobpgallagher** [comment]
Really? My diff is just 
```
diff --git a/demo/src/index.js b/demo/src/index.js
index eca6d6f..0f79501 100644
--- a/demo/src/index.js
+++ b/demo/src/index.js
@@ -66,7 +66,7 @@ export default class Demo extends Component {
             className="oscilloscope"
             record={this.state.record}
             backgroundColor="#FF4081"
-            visualSetting="sinewave"
+            visualSetting="frequencyCircles"
             audioBitsPerSecond= {128000}
             onStop={this.onStop}
             onStart={this.onStart}
```
And then mine looks like
react-mic

**Comment by hackingbeauty** [comment]
Thanks Jacob, this is really cool!!! :)
(I had a typo, that's why it wasn't originally working for me)

**Comment by andriyor** [comment]
Why this merged but I do not see this in the repo?

**Pull request merged**
